# Run when the PR is created, updated with a new commit, or re-opened after closed

name: Pull Request
on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ github.repository }}:${{ github.head_ref }}
      # --------
      # COMMAND TEMPLATE
      # Use this to run a job within your main Dockerfile built app container
      #
      # - name: <job name>
      #   run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app <terminal command>
      # --------
      
      # --------
      # COMMON PR CHECKS
      # Add/remove what you do/don't use. Common ones provided below
      # --------  
      # LINTER
      - name: Run linter
        run: docker-compose -f docker-compose.yml -f ci/docker-compose.ci.yml run app sh ci/linter.sh
      
      # TESTS
      - name: Run tests
        run: docker-compose -f docker-compose.yml -f ci/docker-compose.ci.yml run app sh ci/tests.sh
      
      # SECURITY
      - name: Run security scans
        run: docker-compose -f docker-compose.yml -f ci/docker-compose.ci.yml run app sh ci/security.sh

      # CODE QUALITY
      - name: Run code quality scans
        run: docker-compose -f docker-compose.yml -f ci/docker-compose.ci.yml run app sh ci/code_quality.sh

      # Testing publish script
      - name: Build and publish artifacts
        run: docker run -v "$PWD:/app" -e TF_VAR_bucket_name=${{ secrets.TF_VAR_bucket_name }} -e TF_VAR_domains=${{ secrets.TF_VAR_domains }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e AWS_DEFAULT_REGION=us-east-1 ${{ github.repository }}:${{ github.head_ref }} sh ci/publish_build.sh $(git tag -l --sort "v:refname" "*.*.*" | tail -1)
